x-deploy: &x-deploy-default
  replicas: ${GRAFANA_LOKI_REPLICAS:-3}
  placement:
    max_replicas_per_node: 1
    constraints:
      - node.labels.grafana-loki == true
    preferences:
      - spread: node.labels.grafana-loki
  labels:
    # Prometheus
    io.prometheus.enabled: "true"
    io.prometheus.scrape_port: "3100"
    # Promtail
    io.promtail.enabled: "true"
  update_config:
    parallelism: 1
    delay: 30s
    order: stop-first
    failure_action: rollback
  rollback_config:
    parallelism: 1
    delay: 30s
  restart_policy:
    condition: on-failure
    delay: 30s
    max_attempts: 3
    window: 120s

x-logging: &x-logging-default
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

networks:
  dockerswarm_monitoring:
    name: dockerswarm_monitoring
    external: true

volumes:
  loki:

configs:
  loki.yml:
    template_driver: golang
    file: configs/loki.yml

services:
  loki:
    hostname: loki-{{.Task.Slot}}
    image: grafana/loki:${GRAFANA_LOKI_VERSION:-latest}
    command: 
      - -config.expand-env=true
      - -config.file=/etc/loki/loki.yml
    networks:
      - dockerswarm_monitoring
    ports:
      - ${GRAFANA_LOKI_HTTP_LISTEN_PORT:-3100}:3100 # http_listen_port
      - ${GRAFANA_LOKI_GRPC_LISTEN_PORT:-9195}:9095 # grpc_listen_port
    volumes:
      - loki:/loki
    configs:
      - source: loki.yml
        target: /etc/loki/loki.yml
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy: *x-deploy-default
    logging: *x-logging-default
