x-deploy: &x-deploy-default
  replicas: ${GRAFANA_LOKI_REPLICAS:-3}
  placement:
    max_replicas_per_node: 1
    constraints:
      - node.labels.loki == true
    preferences:
      - spread: node.labels.loki
  update_config:
    parallelism: 1
    delay: 30s
    order: stop-first
    failure_action: rollback
  rollback_config:
    parallelism: 1
    delay: 30s
  restart_policy:
    condition: on-failure
    delay: 30s
    max_attempts: 3
    window: 120s

x-logging: &x-logging-default
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

networks:
  dockerswarm_monitoring:
    name: dockerswarm_monitoring
    external: true

volumes:
  loki:
    external: true

configs:
  loki-config:
    file: configs/loki.yaml

services:
  loki:
    image: grafana/loki:${GRAFANA_LOKI_VERSION:-latest}
    command: 
      - -config.expand-env=true
      - -config.file=/etc/loki/loki.yaml
    networks:
      - dockerswarm_monitoring
    ports:
      - ${GRAFANA_LOKI_PORT:-3100}:3100 # http
      # - 9096:9096 # grpc
      # - 7946:7946 # gossip
    volumes:
      - loki:/loki
    configs:
      - source: loki-config
        target: /etc/loki/loki.yaml
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy: *x-deploy-default
    logging: *x-logging-default
