# Loki defaults to running in multi-tenant mode. Multi-tenant mode is set in the configuration with auth_enabled: true.
# 
# When configured with auth_enabled: false, Loki uses a single tenant. 
# The X-Scope-OrgID header is not required in Loki API requests. 
# The single tenant ID will be the string "fake".
auth_enabled: true

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_server_read_timeout: 310s
  http_server_write_timeout: 310s
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600

common:
  # instance_addr: 127.0.0.1
  instance_interface_names:
    - eth0
    - en0
    - lo
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 3
  ring:
    kvstore:
      prefix: loki/collectors/
      store: consul
      consul:
        host: consul:8500
        acl_token: secret

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: aws
      schema: v12
      index:
        prefix: index_
        period: 24h

storage_config:
  aws:
    s3: http://minio:9000
    region: us-east-1
    bucketnames: loki
    access_key_id: access_key_id
    secret_access_key: secret_access_key
    insecure: true
    sse_encryption: false
    s3forcepathstyle: true

  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
    cache_ttl: 24h
    shared_store: s3

ruler:
  alertmanager_url: http://alertmanager:9093

querier:
  # max_concurrent: 10 # default
  query_timeout: 300s
  engine:
    timeout: 300s

ingester:
  chunk_encoding: snappy
  chunk_idle_period: 2h
  chunk_target_size: 1.5e+6 # 1.4MB
  max_chunk_age: 2h

ingester_client:
  grpc_client_config:
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600


limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

  # See https://grafana.com/docs/loki/latest/operations/storage/retention/
  # The minimum retention period is 24h.
  # retention_period: 744h

memberlist:
  join_members:
    - dns+loki:7946

# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
#
# Statistics help us better understand how Loki is used, and they show us performance
# levels for most users. This helps us prioritize features and documentation.
# For more information on what's sent, look at
# https://github.com/grafana/loki/blob/main/pkg/usagestats/stats.go
# Refer to the buildReport method to see what goes into a report.
#
# If you would like to disable reporting, uncomment the following lines:
analytics:
  reporting_enabled: false
